Traceback (most recent call last):
  File "/home/donald/SuperSploit-V1.0.5/source/core/reconCore/menu.py", line 25, in __init__
    functions[inputs.index(data)](data)
  File "/home/donald/SuperSploit-V1.0.5/source/core/help.py", line 29, in recon
    with open(f".data/.help/{a}", "r") as file:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '.data/.help/wifi'
Traceback (most recent call last):
  File "/home/donald/SuperSploit-V1.0.5/source/core/reconCore/menu.py", line 24, in __init__
    functions[inputs.index(data)](data)
  File "/home/donald/SuperSploit-V1.0.5/source/core/help.py", line 29, in recon
    with open(f".data/.help/{a}", "r") as file:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '.data/.help/wifi'
